# Site settings
title: Whiskey Muzzle
email: stevenmaguire@gmail.com
url: https://whiskeymuzzle.github.io
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#f5ee73'

# Footer settings
footer: Whiskey Muzzle

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty

team:
 - name: Joanna Beer
   url: https://twitter.com/joanna_beer
 - name: Brian Green
   url: https://twitter.com/shrugsworth
 - name: Steven Maguire
   url: https://twitter.com/stevenmaguire
 - name: Eliot Sayles
   url: https://twitter.com/eliotsayles

projects:
 - name: Jinx
   medium: film
   url: http://vimeo.com/stevenmaguire/jinx
   thumbnail: http://whiskeymuzzle.com.s3.amazonaws.com/jinx-thumbnail.png
 - name: ByDre.co
   medium: website
   url: http://bydre.co
   thumbnail: http://whiskeymuzzle.com.s3.amazonaws.com/by-dreco-thumbnail.png
