# Site settings
title: Whiskey Muzzle
email: stevenmaguire@gmail.com
url: https://whiskeymuzzle.com
description: "self-deprecating and hypothetical creative braintrust, attempting to develop ideas into reality"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#f5ee73'

# Footer settings
footer: Whiskey Muzzle

# Social networks usernames (many more available: facebook, stack-overflow, bitbucket, github, google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/WhiskeyMuzzle

# Build settings
markdown: kramdown
permalink: pretty

team:
 - name: Joanna Beer
   url: https://twitter.com/joanna_beer
 - name: Brian Green
   url: https://twitter.com/shrugsworth
 - name: Steven Maguire
   url: https://twitter.com/stevenmaguire
 - name: Eliot Sayles
   url: https://twitter.com/eliotsayles

projects:
 - name: Jinx
   medium: film
   url: http://vimeo.com/stevenmaguire/jinx
   thumbnail: http://s3.amazonaws.com/www.whiskeymuzzle.com/jinx-thumbnail.png
 - name: ByDre.co
   medium: website
   url: http://bydre.co
   thumbnail: http://s3.amazonaws.com/www.whiskeymuzzle.com/by-dreco-thumbnail.png
